site_name: ITSG-33

theme:
  name: material
  palette:
    primary: indigo
    accent: blue

repo_url: https://github.com/Collinbrown95/itsg-33-conftest 

extra:
  social:
    - icon: fontawesome/brands/github 
      link: https://github.com/Collinbrown95/itsg-33-conftest

plugins:
  - search:
      separator: '[\s\-\.]+'

markdown_extensions:
  - pymdownx.snippets
  - pymdownx.highlight:
      linenums: true
  - pymdownx.superfences 

nav:
  - Config Connector:
    - AC 3 (1):
      - Bucket: config_connector/ac_3_1/bucket.md
    - CP 9:
      - SQLInstance: config_connector/cp_9/sqlinstance.md