direction: down

"Organizational Infrastructure": {
  "": |md
    ## Security controls that are in place for the entire organization.
    ## Examples
    - ### Every employee must use MFA with the cloud tenant.
    - ### There is a process for creation/destruction of accounts.
    - ### From which corporate network(s) can employees access the cloud tenant?
  |
}

"Project-Specific Infrastructure": {
  "": |md
    ## Security controls for infrastructure provisioned specifically for a project.
    ## Examples
    - ### Does the storage solution implement backups?
    - ### Does the storage solution implement access control?
    - ### Are project data encrypted at rest?
  |
  style: {
    stroke: red
    stroke-dash: 5
  }
}

Project-Specific Code Artifacts: {
  "": |md
    ## Security controls that address the security of project-specific code.
    ## Examples
    - ### Do project dependencies undergo routine CVE scanning?
    - ### Does source code undergo routine SAST scanning?
    - ### Are unit tests for the source code run regularly?
  |
}

Organizational Infrastructure -> Project-Specific Infrastructure
Project-Specific Infrastructure -> Project-Specific Code Artifacts
